time_keys = {"15": "022025", "30": "032025", "AT": "002025"}
all_stats_names = ["proj"] + list(time_keys.keys())

non_gk_terms = {
    "goals": "13",
    "assists": "14",
    "plus_minus": "15",
    "points": "16",
    "penalty_minutes": "17",
    "power play goals": "18",
    "power play assists": "19",
    "short handed goals": "20",
    "short handed assists": "21",
    "game winning goals": "22",
    "FOW": "23",
    "FOL": "24",
    "proj_26": "26",
    "average_time_on_ice": "27",
    "hatricks": "28",
    "shots_on_goal": "29",
    "games_played": "30",
    "hits": "31",
    "blocks": "32",
    "proj_35": "35",
    "proj_36": "36",
    "special team points": "37",
}
gk_terms = {
    "games_played": "0",
    "wins": "1",
    "losses": "2",
    "shots_at_them": "3",
    "goals against": "4",
    "saves": "6",
    "clean_sheets": "7",
    "average_time_on_ice": "8",
    "over_time_loss": "9",
    "goals against average": "10",
    "save_percent": "11",
    "gk_proj_12": "12",
    "gk_proj_14": "14",
    "gk_proj_16": "16",
}
team_dict = {
    25: "Anaheim Ducks",
    1: "Boston Bruins",
    2: "Buffalo Sabres",
    3: "Calgary Flames",
    7: "Carolina Hurricanes",
    4: "Chicago Blackhawks",
    17: "Colorado Avalanche",
    29: "Columbus Blue Jackets",
    9: "Dallas Stars",
    5: "Detroit Red Wings",
    6: "Edmonton Oilers",
    26: "Florida Panthers",
    8: "Los Angeles Kings",
    30: "Minnesota Wild",
    10: "Montreal Canadiens",
    27: "Nashville Predators",
    11: "New Jersey Devils",
    12: "New York Islanders",
    13: "New York Rangers",
    14: "Ottawa Senators",
    15: "Philadelphia Flyers",
    16: "Pittsburgh Penguins",
    18: "San Jose Sharks",
    124292: "Seattle Kraken",
    19: "St. Louis Blues",
    20: "Tampa Bay Lightning",
    21: "Toronto Maple Leafs",
    129764: "Utah Hockey Club",
    22: "Vancouver Canucks",
    37: "Vegas Golden Knights",
    23: "Washington Capitals",
    28: "Winnipeg Jets",
}
